apiVersion: apps/v1
kind: Deployment
metadata:
  name: poor-registry-deployment
spec:
  selector:
    matchLabels:
      app: poor-registry
  template:
    metadata:
      labels:
        app: poor-registry
    spec:
      containers:
      - name: poor-registry
        image: madhuakula/k8s-goat-poor-registry
        resources:
          limits:
            memory: "50Mi"
            cpu: "30m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: poor-registry-service
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: poor-registry
