apiVersion: v1
kind: Secret
metadata:
  name: goatvault
type: Opaque
data:
  k8sgoatvaultkey: azhzLWdvYXQtY2QyZGEyNzIyNDU5MWRhMmI0OGVmODM4MjZhOGE2YzM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-monitor-deployment
spec:
  selector:
    matchLabels:
      app: system-monitor
  template:
    metadata:
      labels:
        app: system-monitor
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      volumes:
      - name: host-filesystem
        hostPath:
          path: /
      containers:
      - name: system-monitor
        image: madhuakula/k8s-goat-system-monitor
        resources:
          limits:
            memory: "50Mi"
            cpu: "20m"
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: host-filesystem
          mountPath: /host-system
        env:
          - name: K8S_GOAT_VAULT_KEY
            valueFrom:
              secretKeyRef:
                name: goatvault
                key: k8sgoatvaultkey
---
apiVersion: v1
kind: Service
metadata:
  name: system-monitor-service
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: system-monitor
